name: Publish Helm Charts to GHCR

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'
      - '.github/workflows/publish-helm-charts.yaml'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: v3.14.0

      - name: Log in to GHCR
        run: echo "${{ secrets.HELM_PACKAGES_PAT }}" | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Package and Push Charts
        run: |
          CHARTS_DIR="charts"
          for chart in "$CHARTS_DIR"/*; do
            if [ -d "$chart" ]; then
              CHART_NAME=$(basename "$chart")
              echo "Packaging $CHART_NAME..."

              helm dependency update "$chart"
              helm package "$chart" --destination .cr-packages

              CHART_PACKAGE=$(ls .cr-packages/${CHART_NAME}-*.tgz)
              CHART_VERSION=$(helm show chart "$CHART_PACKAGE" | grep '^version:' | awk '{print $2}')

              # Check if chart version already exists in GHCR
              echo "Checking if $CHART_NAME:$CHART_VERSION exists in GHCR..."
              if helm show chart oci://ghcr.io/${{ github.repository_owner }}/$CHART_NAME --version "$CHART_VERSION" > /dev/null 2>&1; then
                echo "$CHART_NAME:$CHART_VERSION already exists in GHCR, skipping push."
              else
                echo "Pushing $CHART_NAME:$CHART_VERSION to GHCR..."
                helm push "$CHART_PACKAGE" oci://ghcr.io/${{ github.repository_owner }}
              fi
            fi
          done
